os:
  - linux
  - windows
sudo: false
language: rust
rust:
- stable
- 1.34.2
- beta
- nightly
matrix:
  include:
    - rust: stable
      env: CARGOFLAGS="--no-default-features"
    - rust: stable
      env: CARGOFLAGS="--no-default-features --features alloc"

script:
- cargo test --verbose $CARGOFLAGS
